//@version=5
library("Exponential Trend [AlgoAlpha]")

expRate = 0.00003
initialDistance = 4.0
widthMultiplier = 1.0

pine_supertrend(float factor, int atrPeriod) =>
    src = hl2
    atr = ta.atr(atrPeriod)
    upperBand = src + factor * atr
    lowerBand = src - factor * atr
    prevLowerBand = nz(lowerBand[1])
    prevUpperBand = nz(upperBand[1])

    lowerBand := lowerBand > prevLowerBand or close[1] < prevLowerBand ? lowerBand : prevLowerBand
    upperBand := upperBand < prevUpperBand or close[1] > prevUpperBand ? upperBand : prevUpperBand
    int _direction = na
    float superTrend = na
    prevSuperTrend = superTrend[1]
    if na(atr[1])
        _direction := 1
    else if prevSuperTrend == prevUpperBand
        _direction := close > upperBand ? -1 : 1
    else
        _direction := close < lowerBand ? 1 : -1
    [upperBand, lowerBand, _direction]

[upper, lower, dir] = pine_supertrend(initialDistance, 14)

var _initial = 0.0
var trend = 0

if bar_index == 100
    if dir < 0
        _initial := lower
        trend := 1
    else
        _initial := upper
        trend := -1

crossoverCondition = ta.crossover(close, _initial)
crossunderCondition = ta.crossunder(close, _initial)

if crossoverCondition
    _initial := lower
    trend := 1    
if crossunderCondition
    _initial := upper
    trend := -1    

barsElapsed = ta.barssince(trend != trend[1])

expMultiplier = math.min(1.0 + trend * (1.0 - math.exp(-expRate * barsElapsed)), 900.0)

_initial := _initial * expMultiplier
volatility = ta.atr(14)
init_ = _initial + (trend > 0 ? volatility * widthMultiplier : -volatility * widthMultiplier)
